#!/bin/bash  


	
log_install=$(pwd)/setup/install.log.out
	
sudo apt-get -y install unzip >> $log_install 2>&1
	
cd setup 
	
echo -e "\033[0;31m $(date) Localhost env preparing..."
wget -O DropSeq.zip https://github.com/broadinstitute/Drop-seq/releases/download/v2.4.0/Drop-seq_tools-2.4.0.zip >> $log_install 2>&1
unzip DropSeq >> $log_install 2>&1
mv Drop-seq_tools-2.4.0 DropSeq >> $log_install 2>&1
rm -r DropSeq.zip >> $log_install 2>&1

cd ..
	
echo -e "\033[0;31m $(date) Docker build starting..."
docker build -t jseq -f Dockerfile .
id=$(docker images --format "{{.ID}}" jseq)
echo $id
echo id=$id > $(pwd)/setup/docker_id
docker run --privileged --rm -it -v $(pwd):/app/JSEQ_scRNAseq $id


