#!/bin/bash

barcode_start=1
barcode_end=16
umi_start=17
umi_end=26


barcode_length=$[$barcode_end-$barcode_start+1]
umi_length=$[$umi_end-$umi_start+1]

barcode='(?P<cell_1>.{'$barcode_length'})(?P<umi_1>.{'$umi_length'})'