#!/bin/bash

barcode_start=1
barcode_end=12
umi_start=13
umi_end=20


barcode_length=$[$barcode_end-$barcode_start+1]
umi_length=$[$umi_end-$umi_start+1]

barcode='(?P<cell_1>.{'$barcode_length'})(?P<umi_1>.{'$umi_length'})'