#!/bin/bash 

echo ''
echo -e '\033[1;36m Docker container'

echo ''
echo ''

function start {

echo ''
echo -e '\033[1;36m Choose JSEQ function:'
echo -e '\033[1;36m -download RefGenome [genome]'
echo -e '\033[1;36m -quit [q]'
echo ''
echo -e '\033[1;36m Choose function:'
echo ''
	read s
	s=$(echo $s | tr '[:upper:]' '[:lower:]')


if [[ $s == 'genome' ]]
then
        source=$(pwd)/scripts/genome_indexing
		source $source
		GENOME
		
		
		
	
elif [[ $s == 'q' ]]
then
        exit
		
fi


}

start