#!/bin/bash
 


function select_project {

INFASTP=$(pwd)/projects/*

select d in $INFASTP; do test -n "$d" && break; echo -e "\033[0;31m >>> Invalid Selection"; done
cd $d
source config
project_name=$project_name 
project_name_mod=$project_name_mod
species=$species
cell=$cell
data=$data
marker_path=$marker_path
library=$library
tissue=$tissue
region=$region
status=$status
health_status=$health_status
sex=$sex
data_format=$data_format

cd ..

cd ..

}

