#!/bin/bash
function merge_fq {
 

fq=$(pwd)/projects/$project_name/fast_data/*.fastq.gz
for i in $fq;
do
if      [[ $i == *"R1"* ]];
then
		r1+=$(basename $i)' '
elif 	[[ $i == *"R2"* ]];
then
		r2+=$(basename $i)' '
fi
done;

cd projects/$project_name/fast_data
cat $r1 > input_R1.fastq.gz
cat $r2 > input_R2.fastq.gz
rm $r1 $r2

r1=
r2=

cd ..
cd ..
cd ..

}


function checkfq {
		echo ''
		echo  -e '\033[1;36m Put fastq data into => projects/'$project_name/'fast_data'
		echo  -e '\033[1;36m If you did it, push ENTER'
		read enter
		
		fast=$(pwd)/projects/$project_name/fast_data/*.fastq.gz
	
for i in $fast;
do
		r+=$i
done;

if      [[ $r == *"R1"* ]] && [[ $r == *"R2"* ]];
then
        echo ''
		echo -e "\033[0;32m Project done"
		echo ''
		echo  -e '\033[1;36m Merge fastq file for Read1 and Read2 - if more than one'
		echo ''
		merge_fq
		echo ''
		source=$(pwd)/scripts/genome_indexing
		source $source
		INDEXING
		
else
        echo -e '\033[0;31m Fastq data not found'
		echo -e '\033[0;31m Put data'
		checkfq
		
fi
 
	
		
}

function checkseurat_1 {
		echo ''
		echo  -e '\033[1;36m Put count genes matrix into => projects/'$project_name/'sc_data'
		echo  -e '\033[1;36m Available matrix format .csv | .tsv | .txt'
		echo  -e '\033[1;36m If you did it, push ENTER'
		read enter
		
		fast=$(pwd)/projects/$project_name/sc_data/*
	
for i in $fast;
do
		r+=$i
done; 		
		
if      [[ $r == *".tsv"* ]]
then

        echo  -e '\033[1;36m $(date) Data converting'
	
	format=tsv
	con=NULL
	null=NULL
	converter=$(pwd)/scripts/converter.R
	Rscript $converter $format $(pwd)/projects/$project_name/sc_data/ $(basename $r) $null $con
	
	
		echo ''
		echo -e "\033[0;32m Project done"
		echo -e "\033[0;32m Start analysis"
		echo ''


	
elif     [[ $r == *".csv"* ]] 
then
        echo  -e '\033[1;36m $(date) Data converting'
	
	format=csv
	con=NULL
	null=NULL
	converter=$(pwd)/scripts/converter.R
	Rscript $converter $format $(pwd)/projects/$project_name/sc_data/ $(basename $r) $null $con
	
		echo ''
		echo -e "\033[0;32m Project done"
		echo -e "\033[0;32m Start analysis"
		echo ''
	
	
	
elif    [[ $r == *".txt"* ]]
then
        
		echo  -e '\033[1;36m $(date) Data converting'
		
	format=txt
	con=NULL
	null=NULL
	converter=$(pwd)/scripts/converter.R
	Rscript $converter $format $(pwd)/projects/$project_name/sc_data/ $(basename $r) $null $con
		
		echo ''
		echo -e "\033[0;32m Project done"
		echo -e "\033[0;32m Start analysis"
		echo ''
	
	
		
		
else
        echo -e '\033[1;31m Expression data not found'
		echo -e '\033[1;31m Put data'
		checkseurat_1
fi

	
		
}



function checkseurat_2 {
		echo ''
		echo  -e '\033[1;36m Put genes name data as genes.tsv into => projects/'$project_name/'sc_data'
		echo  -e '\033[1;36m Put barcodes data as barcodes.tsv into => projects/'$project_name/'sc_data'
		echo  -e '\033[1;36m Put count matrix data as matrix.mtx into => projects/'$project_name/'sc_data'
		echo  -e '\033[1;36m If you did it, push ENTER'
		read enter
		
		fast=$(pwd)/projects/$project_name/sc_data/*
	
for i in $fast;
do
		r+=$i
done; 		
		
if      [[ $r == *"matrix"* ]] && [[ $r == *"genes"* ]] && [[ $r == *"barcodes"* ]];
then
        echo ''
		echo -e "\033[0;32m Project done"
		echo -e "\033[0;32m Start analysis"
		echo ''
		
	
	start
		
		
else
        echo -e '\033[0;31m Expression data not found'
		echo -e '\033[0;31m Put data'
		checkseurat_3
fi

	
		
}
function PARAMETRS {

echo  -e '\033[1;36m Enter operation paramets:'
echo ''
echo  -e '\033[1;36m Reads lenght:'
echo ''
        read READS_LENGHT
echo  -e '\033[1;36m Species [human/mice/custom]:'
echo ''
        read species
		species=$(echo $species | tr '[:upper:]' '[:lower:]')
		echo  -e '\033[1;36m Library type [dropseq/10xV2/10xV3/none]:'
echo ''
        read library
		library=$(echo $library | tr '[:upper:]' '[:lower:]')
		echo  -e '\033[1;36m Tissue [brain/livier/ect]:'
echo ''
        read tissue
		tissue=$(echo $tissue | tr '[:upper:]' '[:lower:]')
		echo  -e '\033[1;36m Region [cortex/striatum/ect.]:'
echo ''
        read region
		region=$(echo $region | tr '[:upper:]' '[:lower:]')
		echo  -e '\033[1;36m Cell development [development/mature]:'
echo ''
		read status
		status=$(echo $status | tr '[:upper:]' '[:lower:]')
		echo  -e '\033[1;36m Cell disease status [disease/healthy]:'
echo ''
		read health_status
		health_status=$(echo $health_status | tr '[:upper:]' '[:lower:]')
		echo  -e '\033[1;36m Sex [male/female/none]:'
echo ''
		read sex
		sex=$(echo $sex | tr '[:upper:]' '[:lower:]')
		echo  -e '\033[1;36m Data format [fastq/matrix/sparse]:'
echo ''
		read data_format
		data_format=$(echo $data_format | tr '[:upper:]' '[:lower:]')


echo  -e '\033[1;36m Estimated number of cells'
echo ''
	read cell

echo  -e '\033[1;36m Choose marker set'
echo ''

marker_input=$(pwd)/requirements_file/*xlsx

select m in $marker_input; do test -n "$m" && break; echo ">>> Invalid Selection"; done
marker_path=$m

echo ''
echo ''

if [[ $READS_LENGHT -lt 300 && $READS_LENGHT -gt 0 ]] && [[ $species == 'human' || $species == 'mice' || $species == 'custom' ]] && [[ $cell -lt 1000000 && $cell -gt 0 ]];
then

echo -e "\033[0;32m Parametrs correct"
echo ''
else
        echo ''
		echo -e '\033[0;31m Wrong parametrs'
		echo -e '\033[0;31m Write right parametrs'
		echo ''
		PARAMETRS
		
fi

}


function data_select {

		if [[ $data_format = 'fastq' ]]
		then
			checkfq
		elif [[ $data_format = 'matrix' ]] 
		then
			checkseurat_1
		elif [[ $data_format = 'sparse' ]]
		then
			checkseurat_2
fi
}

function PROJECT {

		project_name=$id_project
		project_name_mod=$(date +'%d-%m-%Y')'_'$project_name
		mkdir -p projects/$project_name
		mkdir -p projects/$project_name/results
		mkdir -p projects/$project_name/sc_data
		echo ''
		echo -e "\033[0;32m Complete"
		echo ''
        echo  -e '\033[1;36m Next step =>'
		echo ''
		
		echo project_name=$project_name > $(pwd)/projects/$project_name/config
		echo project_name_mod=$project_name_mod >> $(pwd)/projects/$project_name/config
		echo species=$species >> $(pwd)/projects/$project_name/config
		echo cell=$cell >> $(pwd)/projects/$project_name/config
		echo data=$data >> $(pwd)/projects/$project_name/config
		echo marker_path=$marker_path >> $(pwd)/projects/$project_name/config
		echo library=$library > $(pwd)/projects/$project_name/config
		echo tissue=$tissue >> $(pwd)/projects/$project_name/config
		echo region=$region >> $(pwd)/projects/$project_name/config
		echo status=$status >> $(pwd)/projects/$project_name/config
		echo health_status=$health_status >> $(pwd)/projects/$project_name/config
		echo sex=$sex >> $(pwd)/projects/$project_name/config
		echo data_format=$data_format >> $(pwd)/projects/$project_name/config

		data_select
		

}

function PROJECT_ad {

		PARAMETRS

		project_name=$id_project
		project_name_mod=$(date +'%d-%m-%Y')'_'$project_name
		mkdir -p projects/$project_name
		mkdir -p projects/$project_name/results
		mkdir -p projects/$project_name/sc_data
		echo ''
		echo -e "\033[0;32m Complete"
		echo ''
        echo  -e '\033[1;36m Next step =>'
		echo ''
		
		echo project_name=$project_name > $(pwd)/projects/$project_name/config
		echo project_name_mod=$project_name_mod >> $(pwd)/projects/$project_name/config
		echo species=$species >> $(pwd)/projects/$project_name/config
		echo cell=$cell >> $(pwd)/projects/$project_name/config
		echo data=$data >> $(pwd)/projects/$project_name/config
		echo marker_path=$marker_path >> $(pwd)/projects/$project_name/config
		echo library=$library > $(pwd)/projects/$project_name/config
		echo tissue=$tissue >> $(pwd)/projects/$project_name/config
		echo region=$region >> $(pwd)/projects/$project_name/config
		echo status=$status >> $(pwd)/projects/$project_name/config
		echo health_status=$health_status >> $(pwd)/projects/$project_name/config
		echo sex=$sex >> $(pwd)/projects/$project_name/config
		echo data_format=$data_format >> $(pwd)/projects/$project_name/config

		data_select
		

}