#!/bin/bash 


        source=$(pwd)/scripts/projects
		source $source
		PROJECT
		
		
function experiment_selection {
		if [[ $data_format  == 'fastq' && $species  == 'human' ]] || [[ $data_format  == 'fastq' && $species  == 'mice' ]] || [[ $data_format  == 'fastq' && $species  == 'custom' ]];
then
		log=$(pwd)/projects/$project_name_mode/results/process.log.out
        source=$(pwd)/scripts
		source $source/analysis_species
		echo ''
		echo -e "\033[0;34m Process start..."
		echo ''
		echo -e "\033[1;33m WARNING! Depending on data set volume and data heterogeneity a whole analysis can last even several hours" 
		echo ''
		echo -e "\033[0;34m $(date) Trimming of the adapters and quality control of the reads"
		TRIMMING >> $log 2>&1
		echo -e "\033[0;34m $(date) UMIs and barcodes extraction"
		whitelist >> $log 2>&1
		echo -e "\033[0;34m $(date) Starting of the mapping process"
		STAR_MAPPING >> $log 2>&1
		echo -e "\033[0;34m $(date) Adding UMI and barcode tags to bam file"
		add_tags >> $log 2>&1	
		echo -e "\033[0;34m $(date) Annotation to transcriptome regions"
		dropSEQ >> $log 2>&1
		echo -e "\033[0;34m $(date) Detecting and repairing substitution errors in the cell barcodes"
		final_exon >> $log 2>&1
		echo -e "\033[0;34m $(date) Detecting and repairing barcode indexes synthesis errors"
		completed_bam >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating count statistics"
		umi_extract >> $log 2>&1
		umi_expression >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating RNA metrics"
		scRNAmetrics >> $log 2>&1
		metric_plot >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating matrix of counts"
		convert_mtx_umi >> $log 2>&1
		echo -e "\033[0;34m $(date) Counts analysis and creating report"
		seurat >> $log 2>&1
		echo ''
		echo -e "\033[0;32m Process completed"
		echo ''
		echo -e "\033[1;33m Check $project_name_mode for the results (REPORT). If you don't see the REPORT file, so check process.log file for some errors"
		echo ''
		
elif	[[ $species  == 'human' && $data_format  == 'matrix' ]] || [[ $species  == 'mice' && $data_format  == 'matrix' ]] || [[ $species  == 'custom' && $data_format  == 'matrix' ]] || [[ $species  == 'human' && $data_format  == 'sparse' ]] || [[ $species  == 'mice' && $data_format  == 'sparse' ]] || [[ $species  == 'custom' && $data_format  == 'sparse' ]]
then

		log=$(pwd)/projects/$project_name_mode/results/process.log.out
		
		source=$(pwd)/scripts
		source $source/seurat_analysis
		echo ''
		echo -e "\033[0;34m Process start..."
		echo ''
		echo -e "\033[1;33m WARNING! Depending on data set volume and data heterogeneity a whole analysis can last even several hours" 
		echo ''
		echo -e "\033[0;34m $(date) Counts analysis and creating report"	
		seurat_start >> $log 2>&1
		echo ''
		echo -e "\033[0;32m Process completed"
		echo ''
		echo -e "\033[1;33m Check $project_name_mode for the results (REPORT). If you don't see the REPORT file, so check process.log file for some errors"
		echo ''
else
        echo ''
		echo -e "\033[0;31m Experiment failed - check all the data from project"
		echo ''
		
fi
}

experiment_selection

