#!/bin/bash 

function seurat_start {
echo -e '\033[1;36m $(date) Start counts / expression analysis'

data=1

PATH_PROJECT=$(pwd)/projects/$directory_name
MARKERS=$marker_type
tissue=$tissue
cell_development_status=$cell_development_status
project_name=$project_name

SCRIPTS_EXTRACT=$(pwd)/scripts
Rscript $SCRIPTS_EXTRACT/seurat_cluster_species.R $PATH_PROJECT $MARKERS $species $project_name $data $cell $tissue $cell_development_status

cp $SCRIPTS_EXTRACT/manual_species.R $PATH_PROJECT/results
mv $PATH_PROJECT/results/manual_species.R $PATH_PROJECT/results/manual_analysis.R 

mv $PATH_PROJECT/results/Report.html $PATH_PROJECT/Report.html
mv $PATH_PROJECT/results/Results.rde $PATH_PROJECT/Results.rds
mv $PATH_PROJECT/results/manual_analysis.R $PATH_PROJECT/manual_analysis.R
mv $PATH_PROJECT/results/process.log.out $PATH_PROJECT/process.log.out
mv $PATH_PROJECT/results/*.html $PATH_PROJECT/*.html

rm -rf $PATH_PROJECT/results
rm -rf $PATH_PROJECT/tmp



}