#!/bin/bash 

function permission {

echo ''
echo -e '\033[1;36m Write [sudo] to give installation permission'
echo ''

read permission_sudo

$permission_sudo apt-get update
$permission_sudo apt-get upgrade
$permission_sudo apt-get install unzip

}


#python installation

function python {
$permission_sudo apt -y install python3.8
$permission_sudo apt -y install python3-pip
 pip3 install pysam==0.16.0.1
 pip3 install biopython==1.78
 pip3 install umi_tools==1.0.1
 pip3 install numba
 pip3 install umap-learn==0.5.1
}


#r installation

function r_base {

$permission_sudo apt-get update
$permission_sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
$permission_sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
$permission_sudo apt-get update
$permission_sudo apt-get -y install r-base=3.6.3-2
$permission_sudo apt-get -y install curl
$permission_sudo apt-get -y install openssl
$permission_sudo apt-get -y install libcurl4-openssl-dev
$permission_sudo apt-get -y install libhdf5-dev
$permission_sudo apt-get -y install libhdf5-serial-dev
$permission_sudo apt-get -y install h5utils
$permission_sudo apt-get -y install hdf5-tools
$permission_sudo apt-get -y install hdf5-helpers
$permission_sudo apt-get -y install r-cran-httr=1.4.1-1ubuntu1
$permission_sudo apt-get -y install r-cran-leiden=0.3.3+dfsg-1
$permission_sudo apt-get -y install r-cran-igraph=1.2.4.2-2build1
$permission_sudo apt-get -y install r-cran-readxl=1.3.1-2build1
$permission_sudo apt-get -y install r-cran-pheatmap=1.0.12-1
$permission_sudo apt-get -y install r-cran-matrix=1.2-18-1
$permission_sudo apt-get -y install r-cran-tidyverse=1.3.0-1
$permission_sudo apt-get -y install r-cran-doparallel=1.0.15-1
$permission_sudo apt-get -y install r-cran-dosnow=1.0.18-1
$permission_sudo apt-get -y install r-cran-stringr=1.4.0-1
$permission_sudo apt-get -y install r-cran-seurat
$permission_sudo apt-get -y install r-cran-biocmanager
$permission_sudo apt-get -y install r-cran-plotly
$permission_sudo apt-get -y install r-cran-gridextra


$permission_sudo apt-get update


r_req=$(pwd)
$permission_sudo -i Rscript $r_req/r_req.R 

}


#java installation

function java {

#apt-get update
$permission_sudo apt -y install default-jdk

}

#SAMtools installation

function SAMtools {

$permission_sudo apt-get -y install samtools

}

#STAR installation

function STAR {


wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rna-star/rna-star_2.7.3a+dfsg-1build2_amd64.deb 
$permission_sudo dpkg -i rna-star_2.7.3a+dfsg-1build2_amd64.deb 
rm rna-star_2.7.3a+dfsg-1build2_amd64.deb


}


#Installation fastp

function fastp {


wget http://archive.ubuntu.com/ubuntu/pool/universe/f/fastp/fastp_0.20.0+dfsg-1build1_amd64.deb 
$permission_sudo sudo dpkg -i fastp_0.20.0+dfsg-1build1_amd64.deb 
rm fastp_0.20.0+dfsg-1build1_amd64.deb
	
}

#download DropSeq scripts

function DropSeq {

wget -O DropSeq.zip https://github.com/broadinstitute/Drop-seq/releases/download/v2.4.0/Drop-seq_tools-2.4.0.zip
unzip DropSeq
mv Drop-seq_tools-2.4.0 DropSeq
rm -r DropSeq.zip

}

